name: 'Alpha Common DEV'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  plan:
    if: github.event_name == 'pull_request'
    uses: .github/workflows/deploy_process.yml@main
    permissions:
      id-token: write
      contents: read
    with:
      workload_path: src/shared-ap-southeast-2
      terraform_apply: false
    secrets:
      MODULE_DEPLOY_PRIVATE_KEY: ${{ secrets.TF_API_TOKEN }}
  apply:
    if: github.event_name != 'pull_request'
    uses: .github/workflows/deploy_process.yml@main
    permissions:
      id-token: write
      contents: read
    with:
      workload_path: src/shared-ap-southeast-2
      terraform_apply: true
    secrets:
      MODULE_DEPLOY_PRIVATE_KEY: ${{ secrets.TF_API_TOKEN }}
